POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "rose",
    "number": 122938292 
}

###
get http://localhost:3001/api/persons

###
DELETE http://localhost:3001/api/persons/60fa901286e5dc4c5082cc6f

###
get http://localhost:3001/info